#!/usr/bin/zsh

# Aliases

alias ls="lsd"
alias la="ls --long --all --no-symlink"
alias ll="ls --long"
alias lt="ls --tree --no-symlink"

alias cat="bat"
alias less="bat --paging=always"

alias mkd="mkdir -pv"
alias cp="cp -iv"
alias mv="mv -iv"

alias d="dirs -v"
for index ({1..9}) alias "$index"="cd +${index}"; unset index

alias ex="rlwrap ex"
alias v="${EDITOR}"

alias xinstall="doas xbps-install -Su"
alias xremove="doas xbps-remove"
alias xquery="xbps-query -Rs"

alias reboot="doas shutdown -r now"
alias x="${HOME}/.local/bin/start-river"

